### ISSUE TITLE
CCIP-READ: implement CCIP-READ and wildcard support to Argent wallet

### ISSUE THREAD

**Issue by makoto** [ensdomains/pm#14]
Argent interact with ENS directly via smart contract 

https://github.com/argentlabs

**Comment by DarthMike** [comment]
Hello @makoto we're currenlty working on this, will be added to apps, and also to web3.swift library:
https://github.com/argentlabs/web3.swift/pull/208

**Comment by DarthMike** [comment]
Hello @makoto We've released support for ENS offchain both on iOS and Android. Using web3.swift and web3j libs.
